# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36e545f331f563d684642219086bdf583cab87efdf4592399ebd8df775cd998da63ef016384c355a3b2c239269840c03e37b5c095bb2d25fc7ec4aceca12a4fc

test:
  secret_key_base: ae6364b3c93d6c5f0350555ebf7bb2ae6afeab4bcd249cd874bf133a074f885d97e8cdc14c5a8556427e8ef4b016bcdd020e19b6a671fc4cd4744d520677ee3c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
